# Generated by Django 4.2.16 on 2026-10-06 23:31

from django.db import migrations, models
from django.db.models import F


def backfill_approved_at(apps, schema_editor):
    # No approval history exists for artists approved before this field was added,
    # so assume they were approved when they signed up. Correct in Django admin if needed.
    ArtistProfile = apps.get_model('accounts', 'ArtistProfile')
    ArtistProfile.objects.filter(status='approved', approved_at__isnull=True).update(approved_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_application_into_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this artist was (most recently) approved. Artists share the pool of unattributed subscriber money starting from the month they were approved.', null=True),
        ),
        migrations.RunPython(backfill_approved_at, migrations.RunPython.noop),
    ]
