# Generated by Django 4.2.16 on 2026-10-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0005_subscriberprofile_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=100, unique=True)),
                ('billing_reason', models.CharField(blank=True, help_text="Stripe's billing_reason: 'subscription_create' for a first payment, 'subscription_cycle' for a renewal.", max_length=50)),
                ('amount_paid', models.PositiveIntegerField(help_text='In cents.')),
                ('paid_at', models.DateTimeField()),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscribers.subscriberprofile')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-paid_at'],
            },
        ),
    ]
